word_list = [
    'apple',
    'banana',
    'sabahattin ali',
    'headphone',
    'love',
    'arctic monkeys',
    'deftones',
    'chase atlantic',
    'korn',
    'avenged sevenfold',
    'grimes',
    'eminem',
    'yonaka',
    'radiohead',
    'katatonia',
    'ado',
    'mareux',
    'soen',
    'anathema',
    'halsey',
    'skillet',
    'crossfade',
    'joji',
    'seether',
    'coldplay'
]